import './globals.css'
import type { Metadata } from 'next'
import { Inter, Roboto } from 'next/font/google'
import localFont from 'next/font/local'
import NavBar from './NavBar'
import AuthProvider from './auth/Provider'
import GoogleAnaliticsScripts from './GoogleAnaliticsScripts'

/*fonts: las sirve desde local. Al hacer build las descarga y las sirve desde local*/
const inter = Inter({ subsets: ['latin'] })

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '500']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const poppins = localFont({
  src: '../public/fonts/Poppins-Regular.ttf',
  variable: '--font-poppins'  /*para usarlo desde Tailwind*/
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" data-theme="winter">
      <GoogleAnaliticsScripts />
      <body className={poppins.variable/*poppins.className*//*roboto.className*/}>
        <AuthProvider>
          <NavBar />
          <main className='p-5'>
            {children}
          </main>
        </AuthProvider>
      </body>
    </html>
  )
}
